import uuid from 'uuid';

export const projects = [{
  id: uuid.v4(),
  title: "<SimonGT/> (React)",
  gifUrl: '/img/bits/portfolio.gif',
  imgUrl: '/img/bits/portfolio.jpg',
  description: "Used React, JavaScript, CSS Grid + FlexBox to create a responsive portfolio website that alternates page views using React Router.",
  live: 'https://simongt.net/',
  github: 'https://github.com/simongt/react-portfolio/',
  hidden: false,
}, {
  id: uuid.v4(),
  title: "Towers of Hanoi (React)",
  gifUrl: '/img/bits/towers-of-hanoi.gif',
  imgUrl: '/img/bits/towers-of-hanoi.jpg',
  description: "Used React, Redux, CSS Grid Layout and the React DnD API to build a clone of the classic math puzzle, Towers of Hanoi.",
  live: 'https://simongt.github.io/towers-of-hanoi/',
  github: 'https://github.com/simongt/towers-of-hanoi/',
  hidden: false,
}, {
  id: uuid.v4(),
  title: "Connect Four (jQuery)",
  gifUrl: '/img/bits/connect-4.gif',
  imgUrl: '/img/bits/connect-4.jpg',
  description: "Used HTML, CSS Grid, JavaScript (with jQuery) to create Connect Four, a turn-based game where players compete to form a connecting line of four discs on a grid.",
  live: 'https://simongt.github.io/connect-four/',
  github: 'https://github.com/simongt/connect-four/',
  hidden: false,
}, {
  id: uuid.v4(),
  title: "!Pocket (Full-Stack)",
  gifUrl: '/img/bits/not-pocket.gif',
  imgUrl: '/img/bits/not-pocket.jpg',
  description: "Used React, Node, Express and Postgres to create !Pocket, a content-aggregation and discovery platform that lets users manage collections of saved online articles.",
  live: 'https://notpocket.herokuapp.com/',
  github: 'https://github.com/simongt/not-pocket/',
  hidden: false,
}, {
  id: uuid.v4(),
  title: "List Manager (React)",
  gifUrl: '/img/bits/to-do-react.gif',
  imgUrl: '/img/bits/to-do-react.jpg',
  description: "Used React, FlexBox, CSS and SVG's to build List Manager, a responsive, full CRUD app to organize various lists of tasks.",
  live: 'https://simongt.github.io/react-to-do-list/',
  github: 'https://github.com/simongt/react-to-do-list/',
  hidden: false,
}, {
  id: uuid.v4(),
  title: "Tic-Tac-Toe (jQuery)",
  gifUrl: '/img/bits/tic-tac-toe.gif',
  imgUrl: '/img/bits/tic-tac-toe.jpg',
  description: "Used HTML, CSS, FlexBox, JavaScript (with jQuery) to create Tic-Tac-Toe, a turn-based game where players compete to form a connecting line of three X's or O's on a grid.",
  live: 'https://simongt.github.io/tic-tac-toe/',
  github: 'https://github.com/simongt/tic-tac-toe/',
  hidden: false,
}, {
  id: uuid.v4(),
  title: "Duck Hunt (VanillaJS)",
  gifUrl: '/img/bits/duck-hunt.gif',
  imgUrl: '/img/bits/duck-hunt.jpg',
  description: "Used HTML, CSS and JavaScript to create Duck Hunt, a classic light gun game where a player shoots virtual ducks that their faithful hunting dog flushes out.",
  live: 'https://simongt.github.io/duck-hunt/',
  github: 'https://github.com/simongt/duck-hunt/',
  hidden: false,
}, {
  id: uuid.v4(),
  title: "In Focus Media (SmugMug)",
  gifUrl: '/img/bits/infocusmedia-us.gif',
  imgUrl: '/img/bits/infocusmedia-us.jpg',
  description: "Used HTML, CSS, Adobe Creative Suite and SmugMug's CMS to build a customized web platform for a creative media business that specializes in photography, videography, web and graphic design.",
  live: 'https://www.infocusmedia.us/',
  github: 'https://www.infocusmedia.us/',
  hidden: false,
}, {
  id: uuid.v4(),
  title: "iSpot (Full-Stack)",
  gifUrl: '/img/bits/ispot.gif',
  imgUrl: '/img/bits/ispot.jpg',
  description: "Used EJS, Node, Express and Postgres to create iSpot, a content-aggregation and discovery platform that lets users manage collections of saved locations.",
  live: 'https://ispot-app.herokuapp.com/',
  github: 'https://github.com/simongt/ispot/',
  hidden: true,
}, {
  id: uuid.v4(),
  title: "MemorEyes (VanillaJS)",
  gifUrl: '/img/bits/memor-eyes.gif',
  imgUrl: '/img/bits/memor-eyes.jpg',
  description: "Used HTML, CSS + Flexbox, Vanilla JS to build MemorEyes, a game that lets users flip cards to find matching rank pairs.",
  live: 'https://simongt.github.io/memor-eyes/',
  github: 'https://github.com/simongt/memor-eyes/',
  hidden: false,
}, {
  id: uuid.v4(),
  title: "Task List (EJS)",
  gifUrl: '/img/bits/to-do-ejs.gif',
  imgUrl: '/img/bits/to-do-ejs.jpg',
  description: "Used EJS, Node, Express and Postgres to create Task List, a full CRUD app that organizes to-do items.",
  live: 'https://simongt.github.io/ejs-to-do-list/',
  github: 'https://github.com/simongt/ejs-to-do-list/',
  hidden: true,
}, {
  id: uuid.v4(),
  title: "Weather Anywhere (Fetch API)",
  gifUrl: '/img/bits/weather.gif',
  imgUrl: '/img/bits/weather.jpg',
  description: "Used HTML, CSS, JavaScript (with jQuery) and the OpenWeatherMap API to create Weather Anywhere.",
  live: 'https://simongt.github.io/weather-checker/',
  github: 'https://github.com/simongt/weather-checker/',
  hidden: true,
}, {
  id: uuid.v4(),
  title: "",
  gifUrl: '/img/bits/.gif',
  imgUrl: '/img/bits/.jpg',
  description: "",
  live: 'https://',
  github: 'https://github.com/simongt/',
  hidden: true,
}, {
  id: uuid.v4(),
  title: "",
  gifUrl: '/img/bits/.gif',
  imgUrl: '/img/bits/.jpg',
  description: "",
  live: 'https://',
  github: 'https://github.com/simongt/',
  hidden: true,
}];

export default {
  projects
};
